### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by tinkerspy** [ViperX7/Alpaca-Turbo#15]
Installation on Ubuntu 22.04

Install runs without errors, but when accessing the interface there's no reaction to 'hi', the webui.py script gives the following console output.

Any idea what's wrong?

```
[]
[]
[]
/home/alpaca/.local/lib/python3.10/site-packages/gradio/utils.py:951: UserWarning: Expected 1 arguments for function <bound method ChatBotUI.opast_chat_select of <UI.ChatBotUI object at 0x7ff58723ad10>>, received 0.
  warnings.warn(
/home/alpaca/.local/lib/python3.10/site-packages/gradio/utils.py:955: UserWarning: Expected at least 1 arguments for function <bound method ChatBotUI.opast_chat_select of <UI.ChatBotUI object at 0x7ff58723ad10>>, received 0.
  warnings.warn(
/home/alpaca/.local/lib/python3.10/site-packages/gradio/utils.py:951: UserWarning: Expected 1 arguments for function <bound method ChatBotUI.opast_chat_select of <UI.PromptPlayUI object at 0x7ff587260c10>>, received 0.
  warnings.warn(
/home/alpaca/.local/lib/python3.10/site-packages/gradio/utils.py:955: UserWarning: Expected at least 1 arguments for function <bound method ChatBotUI.opast_chat_select of <UI.PromptPlayUI object at 0x7ff587260c10>>, received 0.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://3932fadb3f87e656d9.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
[]
Set the model path in settings
Traceback (most recent call last):
  File "/home/alpaca/.local/lib/python3.10/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/alpaca/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1069, in process_api
    result = await self.call_function(
  File "/home/alpaca/.local/lib/python3.10/site-packages/gradio/blocks.py", line 892, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/alpaca/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/alpaca/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/alpaca/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/alpaca/.local/lib/python3.10/site-packages/gradio/utils.py", line 549, in async_iteration
    return next(iterator)
  File "/home/alpaca/Alpaca-Turbo/UI.py", line 150, in bot
    for out in resp:
  File "/home/alpaca/Alpaca-Turbo/alpaca_turbo.py", line 233, in ask_bot
    for char in opt_stream:
  File "/home/alpaca/Alpaca-Turbo/alpaca_turbo.py", line 209, in streamer
    self.program.recvuntil(">")
AttributeError: 'Assistant' object has no attribute 'program'
```

**Comment by ViperX7** [comment]
![image](https://user-images.githubusercontent.com/38191717/227556886-4b47aea8-2bbf-436b-a155-3219f9dde44c.png)

**Comment by tinkerspy** [comment]
OK, it seems I missed  a step. 
I'm of looking for this model thing...
