### ISSUE TITLE
Error while starting the webui

### ISSUE THREAD

**Issue by SmileX-san** [ViperX7/Alpaca-Turbo#17]
Running "python webui.py" gives the following error:

Traceback (most recent call last):
  File "E:\Alpaca-Turbo\webui.py", line 13, in <module>
    gptui = ChatBotUI(ASSISTANT)
  File "E:\Alpaca-Turbo\UI.py", line 24, in __init__
    self._personas = Personas("./prompts.json")
  File "E:\Alpaca-Turbo\prompts.py", line 14, in __init__
    self.load()
  File "E:\Alpaca-Turbo\prompts.py", line 18, in load
    self.bots = json.load(f)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 452: character maps to <undefined>

**Comment by ViperX7** [comment]
hey can you try removing an emoji from the prompts.json file
i think it should fix this

**Comment by SmileX-san** [comment]
Thanks, it fixed the issue
