### ISSUE TITLE
On mac: wrong architecture?

### ISSUE THREAD

**Issue by Pol-Lanski** [ViperX7/Alpaca-Turbo#6]
I'm getting a couple of errors off the get go when trying to run on Mac:
First warns on start:
```
❯ python webui.py
/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/gradio/utils.py:951: UserWarning: Expected 1 arguments for function <bound method ChatBotUI.on_select of <UI.ChatBotUI object at 0x10ad2ed60>>, received 0.
  warnings.warn(
/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/gradio/utils.py:955: UserWarning: Expected at least 1 arguments for function <bound method ChatBotUI.on_select of <UI.ChatBotUI object at 0x10ad2ed60>>, received 0.
  warnings.warn(
/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/gradio/utils.py:951: UserWarning: Expected 1 arguments for function <bound method ChatBotUI.on_select of <UI.PromptPlayUI object at 0x1230ac0d0>>, received 0.
  warnings.warn(
/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/gradio/utils.py:955: UserWarning: Expected at least 1 arguments for function <bound method ChatBotUI.on_select of <UI.PromptPlayUI object at 0x1230ac0d0>>, received 0.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860
```

And then error directly when prompting anything:

```
starting with ['bin/mac', '--seed', '888777', '-t', '4', '--top_k', '40', '--top_p', '0.9', '--repeat_last_n', '64', '--repeat_penalty', '1.3', '-m', '/Users/lanski/dalai/alpaca/models/7B/ggml-model-q4_0.bin', 
'--interactive-start']
Traceback (most recent call last):
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/gradio/routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1069, in process_api
    result = await self.call_function(
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/gradio/blocks.py", line 892, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/gradio/utils.py", line 549, in async_iteration
    return next(iterator)
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/UI.py", line 115, in bot
    for out in resp:
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/alpaca_turbo.py", line 198, in ask_bot
    _ = self.prep_model() if not self.is_ready else None
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/alpaca_turbo.py", line 178, in prep_model
    self.program = process(self.command, timeout=600)
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/interact.py", line 26, in __init__
    super().__init__(
  File "/Users/lanski/Documents/Code/alpacaGPT/Alpaca-Turbo/venv/lib/python3.9/site-packages/pexpect/popen_spawn.py", line 53, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: 'bin/mac'
```

I asked chatGPT and his response was: 
1. you can ignore the warns
2. However, the second error is more critical and indicates that there is a problem with the subprocess.Popen() function call. Specifically, the error message indicates that the CPU type in the executable is bad, which suggests that the program is trying to execute a binary file that was compiled for a different CPU architecture.

Based on the error message, it seems that the program is trying to execute the file bin/mac which is likely a compiled binary file for macOS. However, the CPU architecture of your machine might not be compatible with this binary file. One possible solution is to recompile the program from source code on your machine, which should generate a binary file that is compatible with your CPU architecture. Alternatively, you can try to obtain a compatible binary file for your machine or modify the program to use a different binary file that is compatible with your machine's CPU architecture.

My mac is an Intel. Is the mac architecture for M1/2?

**Comment by ViperX7** [comment]
Please mark this as fixed if it fixes your issue

**Comment by RedWideWeb** [comment]
@ViperX7 sorry but the link https://github.com/viperx7/alpaca.cpp is not working. Can you post an instruction on how to build this for Intel macs?

**Comment by deelin** [comment]
I think this may be what you're looking for. Correct me if I'm wrong @ViperX7 https://github.com/ViperX7/llama.cpp

**Comment by deelin** [comment]
I'm assuming @ViperX7 forked a repo from here: https://github.com/antimatter15/alpaca.cpp

**Comment by ViperX7** [comment]
@RedWideWeb 
and @deelin 

this issue is no longer there

this post is for the older version of alpaca-Turbo

if you are on intel mac then you are supposed to use the docker install method

if issue persist i encourage to make a new issue
