### ISSUE TITLE
Loading models issue?

### ISSUE THREAD

**Issue by SauerCarey** [ViperX7/Alpaca-Turbo#71]
I'm not really sure what is going on here.  the interface opens up fine, I have the models in the folder, I go to the settings and they appear, i go back to chat and select one, and it tries to open...

Loading model please wait...

and the CLI shows the following...

'NoneType' object has no attribute 'path'
Exception in thread Thread-43 (<lambda>):
Traceback (most recent call last):
  File "D:\AI\Alpaca-Turbox2\Alpaca-Turbo_0.7\alpaca_turbo.py", line 188, in load_model
    self.process = Process(self.command, timeout=10000)
  File "D:\AI\Alpaca-Turbox2\Alpaca-Turbo_0.7\alpaca_turbo.py", line 177, in command
    f"{self.model.path}",
AttributeError: 'NoneType' object has no attribute 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\carey\pyver\py3_10_9\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\carey\pyver\py3_10_9\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AI\Alpaca-Turbox2\Alpaca-Turbo_0.7\utils\model_selector.py", line 91, in <lambda>
    assistant.load_model(),
  File "D:\AI\Alpaca-Turbox2\Alpaca-Turbo_0.7\alpaca_turbo.py", line 210, in load_model
    return f"Failed loading {self.model.path}"
AttributeError: 'NoneType' object has no attribute 'path'

**Comment by SauerCarey** [comment]
also - if there is a discord, where and how can I find it?  I would like that much more than coming and checking here...
